const Teachers = [
  {
    id: 1,
    name: "Cody Fisher",
    role: "Arabic Teacher",
    rating: 3,
    languages: "Arabic, English, Hebrew",
    price: 85,
    status: "new",
    img: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    name: "Cody Fisher",
    role: "Hebrew Teacher",
    rating: 4,
    languages: "Arabic, English, Spanish",
    price: 25,
    img: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    id: 3,
    name: "Sarah Johnson",
    role: "English Teacher",
    rating: 5,
    languages: "English, French",
    price: 50,
    status: "new",
    img: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    id: 4,
    name: "Ahmed Ali",
    role: "Math Teacher",
    rating: 4,
    languages: "Arabic, English",
    price: 40,
    img: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    id: 5,
    name: "Maria Gonzalez",
    role: "Spanish Teacher",
    rating: 5,
    languages: "Spanish, English",
    price: 35,
    status: "new",
    img: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    id: 6,
    name: "David Smith",
    role: "Physics Teacher",
    rating: 3,
    languages: "English",
    price: 60,
    img: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    id: 7,
    name: "Aisha Khan",
    role: "Biology Teacher",
    rating: 4,
    languages: "Urdu, English",
    price: 55,
    status: "new",
    img: "https://randomuser.me/api/portraits/women/7.jpg",
  },
  {
    id: 8,
    name: "William Brown",
    role: "History Teacher",
    rating: 5,
    languages: "English, German",
    price: 45,
    img: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 9,
    name: "Sophie Martin",
    role: "French Teacher",
    rating: 4,
    languages: "French, English",
    price: 38,
    status: "new",
    img: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 10,
    name: "Hiroshi Tanaka",
    role: "Japanese Teacher",
    rating: 5,
    languages: "Japanese, English",
    price: 70,
    img: "https://randomuser.me/api/portraits/men/10.jpg",
  },
];

export default Teachers;
